controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_meals:
    path: /api/meals
    controller: App\Controller\MealController::index
    methods: ['GET']